In [2]:
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [5]:
df.drop_duplicates(['sepal length (cm)'])

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
8                  4.4               2.9                1.4               0.2
11                 4.8               3.4                1.6               0.2
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
27                 5.2               3.5                1.5               0.2
33                 5.5               4.2                1.4               0.2
41                 4.5               2.3                1.3               0.3
48                 5.3               3.7                1.5               0.2
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
54                 6.5               2.8                4.6               1.5
56                 6.3               3.3                4.7               1.6
58                 6.6               2.9                4.6               1.3
61                 5.9               3.0                4.2               1.5
62                 6.0               2.2                4.0               1.0
63                 6.1               2.9                4.7               1.4
64                 5.6               2.9                3.6               1.3
65                 6.7               3.1                4.4               1.4
68                 6.2               2.2                4.5               1.5
76                 6.8               2.8                4.8               1.4
102                7.1               3.0                5.9               2.1
105                7.6               3.0                6.6               2.1
107                7.3               2.9                6.3               1.8
109                7.2               3.6                6.1               2.5
117                7.7               3.8                6.7               2.2
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0

In [7]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [14]:
df[df&<=0.4]

SyntaxError: invalid syntax (3683779039.py, line 1)